/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated.parent'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated.learn'
import { Route as AuthenticatedBadgesRouteImport } from './routes/_authenticated.badges'
import { Route as AuthenticatedQuizLessonIdRouteImport } from './routes/_authenticated.quiz.$lessonId'
import { Route as AuthenticatedLearnLessonIdRouteImport } from './routes/_authenticated.learn.$lessonId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBadgesRoute = AuthenticatedBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizLessonIdRoute =
  AuthenticatedQuizLessonIdRouteImport.update({
    id: '/quiz/$lessonId',
    path: '/quiz/$lessonId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnLessonIdRoute =
  AuthenticatedLearnLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => AuthenticatedLearnRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/parent': typeof AuthenticatedParentRoute
  '/learn/$lessonId': typeof AuthenticatedLearnLessonIdRoute
  '/quiz/$lessonId': typeof AuthenticatedQuizLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/parent': typeof AuthenticatedParentRoute
  '/learn/$lessonId': typeof AuthenticatedLearnLessonIdRoute
  '/quiz/$lessonId': typeof AuthenticatedQuizLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/badges': typeof AuthenticatedBadgesRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRouteWithChildren
  '/_authenticated/parent': typeof AuthenticatedParentRoute
  '/_authenticated/learn/$lessonId': typeof AuthenticatedLearnLessonIdRoute
  '/_authenticated/quiz/$lessonId': typeof AuthenticatedQuizLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/badges'
    | '/learn'
    | '/parent'
    | '/learn/$lessonId'
    | '/quiz/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/badges'
    | '/learn'
    | '/parent'
    | '/learn/$lessonId'
    | '/quiz/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/badges'
    | '/_authenticated/learn'
    | '/_authenticated/parent'
    | '/_authenticated/learn/$lessonId'
    | '/_authenticated/quiz/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/badges': {
      id: '/_authenticated/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AuthenticatedBadgesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/$lessonId': {
      id: '/_authenticated/quiz/$lessonId'
      path: '/quiz/$lessonId'
      fullPath: '/quiz/$lessonId'
      preLoaderRoute: typeof AuthenticatedQuizLessonIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/$lessonId': {
      id: '/_authenticated/learn/$lessonId'
      path: '/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof AuthenticatedLearnLessonIdRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
  }
}

interface AuthenticatedLearnRouteChildren {
  AuthenticatedLearnLessonIdRoute: typeof AuthenticatedLearnLessonIdRoute
}

const AuthenticatedLearnRouteChildren: AuthenticatedLearnRouteChildren = {
  AuthenticatedLearnLessonIdRoute: AuthenticatedLearnLessonIdRoute,
}

const AuthenticatedLearnRouteWithChildren =
  AuthenticatedLearnRoute._addFileChildren(AuthenticatedLearnRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBadgesRoute: typeof AuthenticatedBadgesRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRouteWithChildren
  AuthenticatedParentRoute: typeof AuthenticatedParentRoute
  AuthenticatedQuizLessonIdRoute: typeof AuthenticatedQuizLessonIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBadgesRoute: AuthenticatedBadgesRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRouteWithChildren,
  AuthenticatedParentRoute: AuthenticatedParentRoute,
  AuthenticatedQuizLessonIdRoute: AuthenticatedQuizLessonIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
